spring:
  thymeleaf:
    cache: false # Whether to enable template caching.
    enabled: true # Whether to enable Thymeleaf view resolution for Web frameworks.
    encoding: UTF-8 # Template files encoding.
    mode: HTML5 # Template mode to be applied to templates. See also Thymeleaf's TemplateMode enum.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/high_concurrency?useSSL=false
      username: root
      password: password
      filters: stat
      max-active: 2
      initial-size: 1
      max-wait: 6000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
mybatis:
  type-aliases-package: com.tilkai.highconcurrency.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/tilkai/highconcurrency/dao/*.xml
# Custom redis config.
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  timeout: 3
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3
